name: Fly Deploy Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "scripts/**"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: 'deploy --config ./fly.production.toml --build-arg DATABASE_URL="file:/remixapp/prisma/remix.db?connection_limit=1" --build-arg REPO="remix-run/remix" --build-arg REPO_DOCS_PATH="docs" --build-arg REPO_LATEST_BRANCH="refs/heads/main" --build-arg SITE_URL="https://remix.run" --strategy rolling'
